In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Files to Load
d2000_path = "../Data/Team_Stats/2000_team_defense.csv"
o2000_path = "../Data/Team_Stats/2000_team_offense.csv"
d2001_path = "../Data/Team_Stats/2001_team_defense.csv"
o2001_path = "../Data/Team_Stats/2001_team_offense.csv"
d2002_path = "../Data/Team_Stats/2002_team_defense.csv"
o2002_path = "../Data/Team_Stats/2002_team_offense.csv"
d2003_path = "../Data/Team_Stats/2003_team_defense.csv"
o2003_path = "../Data/Team_Stats/2003_team_offense.csv"
d2004_path = "../Data/Team_Stats/2004_team_defense.csv"
o2004_path = "../Data/Team_Stats/2004_team_offense.csv"

In [3]:
# Read files and store into Pandas data frames
d2000_df = pd.read_csv(d2000_path)
o2000_df = pd.read_csv(o2000_path)
d2001_df = pd.read_csv(d2001_path)
o2001_df = pd.read_csv(o2001_path)
d2002_df = pd.read_csv(d2002_path)
o2002_df = pd.read_csv(o2002_path)
d2003_df = pd.read_csv(d2003_path)
o2003_df = pd.read_csv(o2003_path)
d2004_df = pd.read_csv(d2004_path)
o2004_df = pd.read_csv(o2004_path)

In [4]:
# Fill NaN values with 0
d2000_df = d2000_df.fillna(0)
o2000_df = o2000_df.fillna(0)
d2001_df = d2001_df.fillna(0)
o2001_df = o2001_df.fillna(0)
d2002_df = d2002_df.fillna(0)
o2002_df = o2002_df.fillna(0)
d2003_df = d2003_df.fillna(0)
o2003_df = o2003_df.fillna(0)
d2004_df = d2004_df.fillna(0)
o2004_df = o2004_df.fillna(0)

In [5]:
# Display sample DF for review
d2000_df.head()

,Year_Def,Rk_Def,Tm_Def,Win_Def,Loss_Def,G_Def,PF_Def,Total Yds_Def,Ply_Def,Y/P_Def,...,Rush Yds_Def,Rush TD_Def,Rush Y/A_Def,Rush 1stD_Def,Pen_Def,Pen Yds_Def,1stPy_Def,Sc%_Def,TO%_Def,EXP_Def
0,2000,1,Baltimore Ravens,12,4,16,165,3967,924,4.3,...,970,5,2.7,59,84,535,22,15.5,23.7,431.92
1,2000,2,Tennessee Titans,13,3,16,191,3813,908,4.2,...,1390,7,3.6,62,97,778,19,18.1,13.8,286.03
2,2000,3,Miami Dolphins,11,5,16,226,4636,995,4.7,...,1736,9,4.2,92,86,793,41,22.8,19.7,224.91
3,2000,4,Philadelphia Eagles,11,5,16,245,4820,1055,4.6,...,1830,10,4.0,105,111,936,31,25.1,14.9,222.88
4,2000,5,New York Giants,12,4,16,246,4546,988,4.6,...,1156,7,3.2,62,80,728,31,22.6,15.3,266.17

In [6]:
# Rename columns so they combine when merging
d2000r_df = d2000_df.rename(columns={"Year_Def":"Year","Tm_Def":"Team","Win_Def":"Wins","Loss_Def":"Losses","G_Def":"G"})
o2000r_df = o2000_df.rename(columns={"Year_Off":"Year","Tm_Off":"Team","Win_Off":"Wins","Loss_Off":"Losses","G_Off":"G"})
d2001r_df = d2001_df.rename(columns={"Year_Def":"Year","Tm_Def":"Team","Win_Def":"Wins","Loss_Def":"Losses","G_Def":"G"})
o2001r_df = o2001_df.rename(columns={"Year_Off":"Year","Tm_Off":"Team","Win_Off":"Wins","Loss_Off":"Losses","G_Off":"G"})
d2002r_df = d2002_df.rename(columns={"Year_Def":"Year","Tm_Def":"Team","Win_Def":"Wins","Loss_Def":"Losses","G_Def":"G"})
o2002r_df = o2002_df.rename(columns={"Year_Off":"Year","Tm_Off":"Team","Win_Off":"Wins","Loss_Off":"Losses","G_Off":"G"})
d2003r_df = d2003_df.rename(columns={"Year_Def":"Year","Tm_Def":"Team","Win_Def":"Wins","Loss_Def":"Losses","G_Def":"G"})
o2003r_df = o2003_df.rename(columns={"Year_Off":"Year","Tm_Off":"Team","Win_Off":"Wins","Loss_Off":"Losses","G_Off":"G"})
d2004r_df = d2004_df.rename(columns={"Year_Def":"Year","Tm_Def":"Team","Win_Def":"Wins","Loss_Def":"Losses","G_Def":"G"})
o2004r_df = o2004_df.rename(columns={"Year_Off":"Year","Tm_Off":"Team","Win_Off":"Wins","Loss_Off":"Losses","G_Off":"G"})

In [7]:
o2000r_df.columns

Index(['Year', 'Rk_Off', 'Team', 'Wins', 'Losses', 'G', 'PF_Off',
       'Total Yds_Off', 'Plays_Off', 'Y/P_Off', 'TO_Off', 'FL_Off', '1stD_Off',
       'Cmp_Off', 'Pass Att_Off', 'Pass Yds_Off', 'Pass TD_Off', 'Int_Off',
       'Pass NY/A_Off', 'Pass 1stD_Off', 'Rush Att_Off', 'Rush Yds_Off',
       'Rush TD_Off', 'Rush Y/A_Off', 'Rush 1stD_Off', 'Pen_Off',
       'Pen Yds_Off', '1stPy_Off', 'Sc%_Off', 'TO%_Off', 'EXP_Off'],
      dtype='object')

In [8]:
# Reorder Columns for merge
d2000r_df = d2000r_df[["Year","Team","Wins","Losses","G","Rk_Def","PF_Def","Total Yds_Def","Ply_Def","Y/P_Def","TO_Def","FL_Def","Total 1stD_Def","Cmp_Def","Pass Att_Def","Pass Yds_Def","Pass TD_Def","Int_Def","Pass NY/A_Def","Pass 1stD_Def","Rush Att_Def","Rush Yds_Def","Rush TD_Def","Rush Y/A_Def","Rush 1stD_Def","Pen_Def","Pen Yds_Def","1stPy_Def","Sc%_Def","TO%_Def","EXP_Def"]]
o2000r_df = o2000r_df[["Year","Team","Wins","Losses","G","Rk_Off","PF_Off","Total Yds_Off","Plays_Off","Y/P_Off","TO_Off","FL_Off","1stD_Off","Cmp_Off","Pass Att_Off","Pass Yds_Off","Pass TD_Off","Int_Off","Pass NY/A_Off","Pass 1stD_Off","Rush Att_Off","Rush Yds_Off","Rush TD_Off","Rush Y/A_Off","Rush 1stD_Off","Pen_Off","Pen Yds_Off","1stPy_Off","Sc%_Off","TO%_Off","EXP_Off"]]
d2001r_df = d2001r_df[["Year","Team","Wins","Losses","G","Rk_Def","PF_Def","Total Yds_Def","Ply_Def","Y/P_Def","TO_Def","FL_Def","Total 1stD_Def","Cmp_Def","Pass Att_Def","Pass Yds_Def","Pass TD_Def","Int_Def","Pass NY/A_Def","Pass 1stD_Def","Rush Att_Def","Rush Yds_Def","Rush TD_Def","Rush Y/A_Def","Rush 1stD_Def","Pen_Def","Pen Yds_Def","1stPy_Def","Sc%_Def","TO%_Def","EXP_Def"]]
o2001r_df = o2001r_df[["Year","Team","Wins","Losses","G","Rk_Off","PF_Off","Total Yds_Off","Plays_Off","Y/P_Off","TO_Off","FL_Off","1stD_Off","Cmp_Off","Pass Att_Off","Pass Yds_Off","Pass TD_Off","Int_Off","Pass NY/A_Off","Pass 1stD_Off","Rush Att_Off","Rush Yds_Off","Rush TD_Off","Rush Y/A_Off","Rush 1stD_Off","Pen_Off","Pen Yds_Off","1stPy_Off","Sc%_Off","TO%_Off","EXP_Off"]]
d2002r_df = d2002r_df[["Year","Team","Wins","Losses","G","Rk_Def","PF_Def","Total Yds_Def","Ply_Def","Y/P_Def","TO_Def","FL_Def","Total 1stD_Def","Cmp_Def","Pass Att_Def","Pass Yds_Def","Pass TD_Def","Int_Def","Pass NY/A_Def","Pass 1stD_Def","Rush Att_Def","Rush Yds_Def","Rush TD_Def","Rush Y/A_Def","Rush 1stD_Def","Pen_Def","Pen Yds_Def","1stPy_Def","Sc%_Def","TO%_Def","EXP_Def"]]
o2002r_df = o2002r_df[["Year","Team","Wins","Losses","G","Rk_Off","PF_Off","Total Yds_Off","Plays_Off","Y/P_Off","TO_Off","FL_Off","1stD_Off","Cmp_Off","Pass Att_Off","Pass Yds_Off","Pass TD_Off","Int_Off","Pass NY/A_Off","Pass 1stD_Off","Rush Att_Off","Rush Yds_Off","Rush TD_Off","Rush Y/A_Off","Rush 1stD_Off","Pen_Off","Pen Yds_Off","1stPy_Off","Sc%_Off","TO%_Off","EXP_Off"]]
d2003r_df = d2003r_df[["Year","Team","Wins","Losses","G","Rk_Def","PF_Def","Total Yds_Def","Ply_Def","Y/P_Def","TO_Def","FL_Def","Total 1stD_Def","Cmp_Def","Pass Att_Def","Pass Yds_Def","Pass TD_Def","Int_Def","Pass NY/A_Def","Pass 1stD_Def","Rush Att_Def","Rush Yds_Def","Rush TD_Def","Rush Y/A_Def","Rush 1stD_Def","Pen_Def","Pen Yds_Def","1stPy_Def","Sc%_Def","TO%_Def","EXP_Def"]]
o2003r_df = o2003r_df[["Year","Team","Wins","Losses","G","Rk_Off","PF_Off","Total Yds_Off","Plays_Off","Y/P_Off","TO_Off","FL_Off","1stD_Off","Cmp_Off","Pass Att_Off","Pass Yds_Off","Pass TD_Off","Int_Off","Pass NY/A_Off","Pass 1stD_Off","Rush Att_Off","Rush Yds_Off","Rush TD_Off","Rush Y/A_Off","Rush 1stD_Off","Pen_Off","Pen Yds_Off","1stPy_Off","Sc%_Off","TO%_Off","EXP_Off"]]
d2004r_df = d2004r_df[["Year","Team","Wins","Losses","G","Rk_Def","PF_Def","Total Yds_Def","Ply_Def","Y/P_Def","TO_Def","FL_Def","Total 1stD_Def","Cmp_Def","Pass Att_Def","Pass Yds_Def","Pass TD_Def","Int_Def","Pass NY/A_Def","Pass 1stD_Def","Rush Att_Def","Rush Yds_Def","Rush TD_Def","Rush Y/A_Def","Rush 1stD_Def","Pen_Def","Pen Yds_Def","1stPy_Def","Sc%_Def","TO%_Def","EXP_Def"]]
o2004r_df = o2004r_df[["Year","Team","Wins","Losses","G","Rk_Off","PF_Off","Total Yds_Off","Plays_Off","Y/P_Off","TO_Off","FL_Off","1stD_Off","Cmp_Off","Pass Att_Off","Pass Yds_Off","Pass TD_Off","Int_Off","Pass NY/A_Off","Pass 1stD_Off","Rush Att_Off","Rush Yds_Off","Rush TD_Off","Rush Y/A_Off","Rush 1stD_Off","Pen_Off","Pen Yds_Off","1stPy_Off","Sc%_Off","TO%_Off","EXP_Off"]]

In [9]:
# Combine Year DFs into single DF
y2000_df = o2000r_df.merge(d2000r_df, how='inner')
y2001_df = o2001r_df.merge(d2001r_df, how='inner')
y2002_df = o2002r_df.merge(d2002r_df, how='inner')
y2003_df = o2003r_df.merge(d2003r_df, how='inner')
y2004_df = o2004r_df.merge(d2004r_df, how='inner')

In [10]:
# Display one combined DF for error checking
y2004_df

,Year,Team,Wins,Losses,G,Rk_Off,PF_Off,Total Yds_Off,Plays_Off,Y/P_Off,...,Rush Yds_Def,Rush TD_Def,Rush Y/A_Def,Rush 1stD_Def,Pen_Def,Pen Yds_Def,1stPy_Def,Sc%_Def,TO%_Def,EXP_Def
0,2004,Indianapolis Colts,12,4,16,1,522,6475,968,6.7,...,2037,12,4.6,103,116,877,19,35.4,18.5,50.75
1,2004,Kansas City Chiefs,7,9,16,2,483,6695,1089,6.1,...,1834,18,4.6,97,117,957,40,38.8,10.9,6.49
2,2004,San Diego Chargers,12,4,16,3,446,5542,996,5.6,...,1307,15,3.7,79,109,940,41,29.5,17.5,66.50
3,2004,New England Patriots,14,2,16,4,437,5722,1035,5.5,...,1572,9,3.9,83,118,1014,30,24.0,20.0,244.33
4,2004,Green Bay Packers,10,6,16,5,424,6357,1053,6.0,...,1878,12,4.6,92,112,942,34,34.3,7.7,20.76
5,2004,Minnesota Vikings,8,8,16,6,405,6339,985,6.4,...,2006,15,4.6,110,110,974,20,41.6,13.3,0.82
6,2004,Buffalo Bills,9,7,16,7,395,4691,982,4.8,...,1604,6,3.6,79,120,865,29,27.6,19.3,253.88
7,2004,Philadelphia Eagles,13,3,16,8,386,5618,960,5.9,...,1903,13,4.3,101,119,1001,33,25.1,13.1,158.04
8,2004,Denver Broncos,10,6,16,9,381,6332,1070,5.9,...,1512,16,3.8,83,120,1062,22,28.1,9.9,126.08
9,2004,Cincinnati Bengals,8,8,16,10,374,5140,1004,5.1,...,2062,11,4.4,123,106,887,22,31.8,16.4,169.40
10,2004,Pittsburgh Steelers,15,1,16,11,372,5184,1012,5.1,...,1299,8,3.6,79,104,875,23,25.9,17.2,201.08
11,2004,Seattle Seahawks,9,7,16,12,371,5634,1034,5.4,...,2031,17,4.5,102,91,748,18,35.2,18.1,87.63
12,2004,Carolina Panthers,7,9,16,13,355,5225,991,5.3,...,1904,19,4.0,98,117,1078,32,30.5,19.8,148.93
13,2004,New Orleans Saints,8,8,16,14,348,5193,989,5.3,...,2253,16,4.6,118,119,965,32,36.6,16.5,20.21
14,2004,Tennessee Titans,5,11,16,15,344,5487,1053,5.2,...,1917,18,4.6,99,95,774,30,36.5,14.6,25.50
15,2004,Atlanta Falcons,11,5,16,16,340,5084,969,5.2,...,1681,20,3.9,107,129,930,20,29.7,16.8,133.45
16,2004,New York Jets,10,6,16,17,333,5438,996,5.5,...,1566,8,3.6,87,86,720,26,25.3,16.9,180.71
17,2004,Oakland Raiders,5,11,16,18,320,5153,939,5.5,...,2012,21,3.7,115,102,837,42,37.2,9.8,3.93
18,2004,St. Louis Rams,8,8,16,19,319,5877,1011,5.8,...,2179,13,4.5,118,109,827,21,37.6,7.7,23.59
19,2004,Baltimore Ravens,9,7,16,20,317,4375,991,4.4,...,1681,9,3.6,88,101,796,26,24.6,16.6,267.76
20,2004,Houston Texans,7,9,16,21,309,5128,1001,5.1,...,1843,4,4.4,89,123,979,21,32.6,16.9,98.16
21,2004,New York Giants,6,10,16,22,303,4722,951,5.0,...,2157,13,4.3,112,120,1007,28,31.9,14.7,72.08
22,2004,Tampa Bay Buccaneers,5,11,16,23,301,4963,949,5.2,...,1973,8,4.1,101,112,897,26,26.2,13.4,216.56
23,2004,Detroit Lions,6,10,16,24,296,4693,949,4.9,...,1887,10,3.8,118,114,976,35,29.6,12.2,89.24
24,2004,Dallas Cowboys,6,10,16,25,293,5197,1004,5.2,...,1764,14,4.2,88,104,879,29,35.7,10.8,48.18
25,2004,Arizona Cardinals,6,10,16,26,284,4550,1047,4.3,...,2105,12,4.7,101,139,1121,28,27.1,14.8,162.40
26,2004,Cleveland Browns,4,12,16,27,276,4481,921,4.9,...,2314,22,4.3,141,109,890,22,32.3,12.3,104.72
27,2004,Miami Dolphins,4,12,16,28,275,4404,1022,4.3,...,2302,12,4.3,107,107,852,35,25.4,11.2,158.56
28,2004,Jacksonville Jaguars,9,7,16,29,261,5009,991,5.1,...,1777,7,4.1,83,118,966,26,26.4,16.1,86.29
29,2004,San Francisco 49ers,2,14,16,30,259,4585,1026,4.5,...,1995,22,4.0,121,107,867,22,37.9,9.7,36.51
30,2004,Washington Redskins,6,10,16,31,240,4397,1023,4.3,...,1304,7,3.1,67,97,797,31,20.7,12.6,202.79
31,2004,Chicago Bears,5,11,16,32,231,3816,967,3.9,...,2050,9,4.1,109,120,914,28,26.9,13.4,199.63

In [11]:
# Combine annual DFs into one combined DF
combined_df = y2000_df[:31].append([y2001_df[:31], y2002_df[:32], y2003_df[:32], y2004_df[:32]])
combined_df

,Year,Team,Wins,Losses,G,Rk_Off,PF_Off,Total Yds_Off,Plays_Off,Y/P_Off,...,Rush Yds_Def,Rush TD_Def,Rush Y/A_Def,Rush 1stD_Def,Pen_Def,Pen Yds_Def,1stPy_Def,Sc%_Def,TO%_Def,EXP_Def
0,2000,St. Louis Rams,10,6,16,1,540,7075,1014,7.0,...,1697,18,4.4,95,101,747,31,40.9,12.4,21.56
1,2000,Denver Broncos,11,5,16,2,485,6554,1115,5.9,...,1598,13,4.6,80,109,898,25,30.2,20.8,104.83
2,2000,Oakland Raiders,12,4,16,3,479,5776,1023,5.6,...,1551,8,4.0,85,117,912,33,26.9,18.7,185.58
3,2000,Indianapolis Colts,10,6,16,4,429,6141,1026,6.0,...,1935,13,4.3,109,103,820,24,31.1,11.7,64.32
4,2000,Minnesota Vikings,11,5,16,5,397,5961,958,6.2,...,1788,17,4.5,110,104,747,26,38.2,9.4,2.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2004,Miami Dolphins,4,12,16,28,275,4404,1022,4.3,...,2302,12,4.3,107,107,852,35,25.4,11.2,158.56
28,2004,Jacksonville Jaguars,9,7,16,29,261,5009,991,5.1,...,1777,7,4.1,83,118,966,26,26.4,16.1,86.29
29,2004,San Francisco 49ers,2,14,16,30,259,4585,1026,4.5,...,1995,22,4.0,121,107,867,22,37.9,9.7,36.51
30,2004,Washington Redskins,6,10,16,31,240,4397,1023,4.3,...,1304,7,3.1,67,97,797,31,20.7,12.6,202.79
31,2004,Chicago Bears,5,11,16,32,231,3816,967,3.9,...,2050,9,4.1,109,120,914,28,26.9,13.4,199.63

In [12]:
#Write combined DataFrame to .csv
combined_df.to_csv("../Data/Team_Stats/2000-2004_cleaned_data.csv",index=False)