In [1]:
import pandas as pd

In [2]:
df_2000_2004 = pd.read_csv("../Data/Team_Stats/2000-2004.csv")
df_2005_2009 = pd.read_csv("../Data/Team_Stats/2005-2009_cleaned_data.csv")
df_2010_2014 = pd.read_csv("../Data/Team_Stats/2010to2014Combined.csv")
df_2015_2019 = pd.read_csv("../Data/Team_Stats/2015-2019_cleaned_data.csv")

In [3]:
combined_df = df_2000_2004[:158].append([df_2005_2009[:160], df_2010_2014[:160], df_2015_2019[:160]])
combined_df

,Year,Rk_Off,Team,Wins,Losses,G,PF_Off,Total Yds_Off,Plays_Off,Y/P_Off,...,Year_Off,Tm_Off,Win_Off,Loss_Off,G_Off,Year_Def,Tm_Def,Win_Def,Loss_Def,G_Def
0,2000.0,1,St. Louis Rams,10.0,6.0,16.0,540,7075,1014,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000.0,2,Denver Broncos,11.0,5.0,16.0,485,6554,1115,5.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000.0,3,Oakland Raiders,12.0,4.0,16.0,479,5776,1023,5.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000.0,4,Indianapolis Colts,10.0,6.0,16.0,429,6141,1026,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000.0,5,Minnesota Vikings,11.0,5.0,16.0,397,5961,958,6.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,NaN,28,NaN,NaN,NaN,NaN,282,4777,954,5.0,...,2019.0,Denver Broncos,7.0,9.0,16.0,2019.0,Denver Broncos,7.0,9.0,16.0
156,NaN,29,NaN,NaN,NaN,NaN,280,4749,1020,4.7,...,2019.0,Chicago Bears,8.0,8.0,16.0,2019.0,Chicago Bears,8.0,8.0,16.0
157,NaN,30,NaN,NaN,NaN,NaN,279,5169,1049,4.9,...,2019.0,Cincinnati Bengals,2.0,14.0,16.0,2019.0,Cincinnati Bengals,2.0,14.0,16.0
158,NaN,31,NaN,NaN,NaN,NaN,276,4368,956,4.6,...,2019.0,New York Jets,7.0,9.0,16.0,2019.0,New York Jets,7.0,9.0,16.0
159,NaN,32,NaN,NaN,NaN,NaN,266,4395,885,5.0,...,2019.0,Washington Redskins,3.0,13.0,16.0,2019.0,Washington Redskins,3.0,13.0,16.0

In [4]:
combined_df['Overall Production'] = ""
combined_df

,Year,Rk_Off,Team,Wins,Losses,G,PF_Off,Total Yds_Off,Plays_Off,Y/P_Off,...,Tm_Off,Win_Off,Loss_Off,G_Off,Year_Def,Tm_Def,Win_Def,Loss_Def,G_Def,Overall Production
0,2000.0,1,St. Louis Rams,10.0,6.0,16.0,540,7075,1014,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,2000.0,2,Denver Broncos,11.0,5.0,16.0,485,6554,1115,5.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,2000.0,3,Oakland Raiders,12.0,4.0,16.0,479,5776,1023,5.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,2000.0,4,Indianapolis Colts,10.0,6.0,16.0,429,6141,1026,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,2000.0,5,Minnesota Vikings,11.0,5.0,16.0,397,5961,958,6.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,NaN,28,NaN,NaN,NaN,NaN,282,4777,954,5.0,...,Denver Broncos,7.0,9.0,16.0,2019.0,Denver Broncos,7.0,9.0,16.0,
156,NaN,29,NaN,NaN,NaN,NaN,280,4749,1020,4.7,...,Chicago Bears,8.0,8.0,16.0,2019.0,Chicago Bears,8.0,8.0,16.0,
157,NaN,30,NaN,NaN,NaN,NaN,279,5169,1049,4.9,...,Cincinnati Bengals,2.0,14.0,16.0,2019.0,Cincinnati Bengals,2.0,14.0,16.0,
158,NaN,31,NaN,NaN,NaN,NaN,276,4368,956,4.6,...,New York Jets,7.0,9.0,16.0,2019.0,New York Jets,7.0,9.0,16.0,
159,NaN,32,NaN,NaN,NaN,NaN,266,4395,885,5.0,...,Washington Redskins,3.0,13.0,16.0,2019.0,Washington Redskins,3.0,13.0,16.0,

In [6]:
for index, row in combined_df.iterrows():
    off_yards = combined_df['Total Yds_Off']
    def_yards = combined_df['Total Yds_Def']
    
    combined_df.loc[index, "Overall Production"] = off_yards - def_yards

ValueError: cannot reindex from a duplicate axis