In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../Data/Team_Stats/2000-2019_cleaned_data3.csv")

In [8]:
df

,Year,Rk_Off,Team,Win,Loss,Games,PF_Off,Total Yds_Off,Plays_Off,Y/P_Off,...,Pen_Def,Pen Yds_Def,1stPy_Def,Sc%_Def,TO%_Def,EXP_Def,Overall Production,Win/Loss_Pct,PPG_Off,PPG_Def
0,2000,1,St. Louis Rams,10,6,16,540,7075,1014,7.0,...,101,747,31,40.9,12.4,21.56,1581,0.6250,33.7500,29.4375
1,2000,2,Denver Broncos,11,5,16,485,6554,1115,5.9,...,109,898,25,30.2,20.8,104.83,1010,0.6875,30.3125,23.0625
2,2000,3,Oakland Raiders,12,4,16,479,5776,1023,5.6,...,117,912,33,26.9,18.7,185.58,527,0.7500,29.9375,18.6875
3,2000,4,Indianapolis Colts,10,6,16,429,6141,1026,6.0,...,103,820,24,31.1,11.7,64.32,784,0.6250,26.8125,20.3750
4,2000,5,Minnesota Vikings,11,5,16,397,5961,958,6.2,...,104,747,26,38.2,9.4,2.03,260,0.6875,24.8125,23.1875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,2019,28,Denver Broncos,7,9,16,282,4777,954,5.0,...,121,1041,34,37.3,8.4,-35.98,-615,0.4375,17.6250,19.7500
634,2019,29,Chicago Bears,8,8,16,280,4749,1020,4.7,...,113,923,30,31.5,10.7,-4.15,-437,0.5000,17.5000,18.6250
635,2019,30,Cincinnati Bengals,2,14,16,279,5169,1049,4.9,...,122,988,21,39.8,8.8,-132.66,-1130,0.1250,17.4375,26.2500
636,2019,31,New York Jets,7,9,16,276,4368,956,4.6,...,107,902,40,34.4,10.1,-0.06,-802,0.4375,17.2500,22.4375
637,2019,32,Washington Redskins,3,13,16,266,4395,885,5.0,...,94,805,34,41.9,12.2,-135.83,-1767,0.1875,16.6250,27.1875

In [10]:
col_list = ["Year", "Team", "PPG_Off", "PPG_Def"]
ppg_df = df[col_list]
ppg_df

     Year                 Team  PPG_Off  PPG_Def
0    2000       St. Louis Rams  33.7500  29.4375
1    2000       Denver Broncos  30.3125  23.0625
2    2000      Oakland Raiders  29.9375  18.6875
3    2000   Indianapolis Colts  26.8125  20.3750
4    2000    Minnesota Vikings  24.8125  23.1875
..    ...                  ...      ...      ...
633  2019       Denver Broncos  17.6250  19.7500
634  2019        Chicago Bears  17.5000  18.6250
635  2019   Cincinnati Bengals  17.4375  26.2500
636  2019        New York Jets  17.2500  22.4375
637  2019  Washington Redskins  16.6250  27.1875

[638 rows x 4 columns]

In [11]:
ppg_df.to_csv('../Data/Team_Stats/ppg_data.csv', index = False)